export const mockData = {
    images: {
        G2Logo: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/G2Logo.png?alt=media&token=9c11895c-dcd5-4660-9de4-f539374c07e6',
        avatarNull: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/avatar.png?alt=media&token=78359aaf-5651-4c63-b72b-86e69f31716c',
        imgVNPAY: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/imgVNPAY.png?alt=media&token=101979ad-cb81-4608-a2e6-e784af830fdc',
        vnpay: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/vnpay.png?alt=media&token=df995743-c8de-4317-af0b-1d91daba9a13',
        thanks: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/thanks.gif?alt=media&token=01e515e3-3e4b-4db0-ae99-c731a2499b60',
        sale: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/sale.jpg?alt=media&token=0ab43dc6-9e64-4ee1-8f22-0bda2d6e481e',
        payment: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/payment.png?alt=media&token=396a265e-5467-4eb7-8888-180bd16e1ecf',
        shopDesign: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/shopDesign.png?alt=media&token=fab551da-2ecb-4b7c-9e0a-199c4d8b993a',
        loginImage: 'https://firebasestorage.googleapis.com/v0/b/g2store-956cf.appspot.com/o/loginImage.jpg?alt=media&token=98e4f1cc-12f3-4346-ab4c-8b0f02ae425e',

    },
    notifications: [
        {
          'notification_id': 1,
          'content': 'Your order has been shipped',
          'created_date': '2024-07-08T10:15:30',
          'is_read': false,
          'is_public': true,
          'customer_id': 1,
          'seller_id': 456
        },
        {
            'notification_id': 2,
            'content': 'Your order has been shipped',
            'created_date': '2024-07-08T10:15:30',
            'is_read': false,
            'is_public': true,
            'customer_id': 1,
            'seller_id': 4
        },

    ],
    promotions: [
        {
            _id: 'promotion-id-01',
            name: 'Omachi Sốt Spaghetty',
            image: 'https://cdn-www.vinid.net/2020/10/c82b07dc-c%C3%A1ch-n%E1%BA%A5u-m%C3%AC-omachi-ngon.jpg'
        },
        {
            _id: 'promotion-id-02',
            name: 'Hảo hảo Chua Cay',
            image: 'https://poongsankorea.vn/medias/e51/images/2022/07/1-goi-mi-hao-hao-bao-nhieu-calo-1-1.jpg'
        },
        {
            _id: 'promotion-id-03',
            name: 'Miến phú hương',
            image: 'https://cdn.fast.vn/tmp/20200919065808-mien-phu-huong-thit-heo-nau-mang-1.jpg'
        },
        {
            _id: 'promotion-id-04',
            name: 'Mì hải sản siêu cay',
            image: 'https://bizweb.dktcdn.net/100/345/470/products/4261222092-1974521184.jpg?v=1584683941813'
        }

    ],
    listProductKeyWords : [
        'Bánh trung thu',
        'Bánh snack',
        'Bánh bông lan',
        'Bánh mì',
        'Bánh gạo',
        'Điện thoại',
        'Điện thoại thông minh',
        'Điện thoại oppo',
        'Điện thoại xiaomi',
        'Điện thoại samsung',
        'Điện thoại iphone',
        'Điện thoại vivo',
        'Laptop văn phòng',
        'Laptop Dell',
        'Laptop Asus',
        'Laptop Gaming',
        'Laptop Surface',
        'Laptop Apple',
        'Laptop Acer',
        'Laptop iTel',
        'Laptop Lenovo',
        'Gấu bông',
        'Điện thoại Redmi Note',
        'Điện thoại XIAOMI 14',
        'Điện thoại OPPO RENO8',
        'Điện thoại Oppo Reno4',
        'Điện thoại OPPO Reno11',
        'Điện thoại oppo reno 8',
        'Điện thoại Apple Iphone 15',
        'Áo thun nữ',
        'Áo thun nam',
        'Snack Lays',
        'SamSung S23 Ultra',
        'Pepsi',
        'Nước ngọt',
        'Nước khoáng',
        'Nước ngọt Fanta',
        'Máy tính laptop CGO',
        'Gấu bông Doraemon',
        'Coca Cola',
        'Bánh quy',
        'Bánh quy sô cô la',
        'Kẹo dẻo',
        'Kẹo',
        'Kẹo socola',
        'Kẹo cao su',
        'Sữa tươi',
        'Sữa chua',
        'Sữa chua có đường',
        'Sữa chua không đường',
        'Trà sữa',
        'Trà xanh',
        'Trà đen',
        'Cà phê',
        'Cà phê đen',
        'Cà phê sữa',
        'Nước ép trái cây',
        'Nước dừa',
        'Nước khoáng',
        'Nước tinh khiết',
        'Nước tăng lực',
        'Nước giải khát',
        'Máy tính bảng Apple',
        'Máy tính bảng Samsung',
        'Máy tính bảng Lenovo',
        'Máy tính bảng Asus',
        'Máy tính bảng Huawei',
        'Đồng hồ Apple Watch',
        'Đồng hồ Samsung Galaxy',
        'Đồng hồ thông minh',
        'Đồng hồ thể thao',
        'Tai nghe AirPods',
        'Tai nghe Sony',
        'Tai nghe Bluetooth',
        'Loa Bluetooth',
        'Loa JBL',
        'Loa Sony',
        'Máy ảnh Canon',
        'Máy ảnh Nikon',
        'Máy ảnh Sony',
        'Máy quay GoPro',
        'Máy quay phim',
        'Máy tính để bàn',
        'Máy tính all-in-one',
        'Máy in HP',
        'Máy in Canon',
        'Máy in Epson',
        'Máy in Brother',
        'TV Samsung',
        'TV LG',
        'TV Sony',
        'TV Panasonic',
        'TV TCL',
        'Tủ lạnh Toshiba',
        'Tủ lạnh Samsung',
        'Tủ lạnh LG',
        'Tủ lạnh Panasonic',
        'Máy giặt Samsung',
        'Máy giặt LG',
        'Máy giặt Toshiba',
        'Máy giặt Electrolux',
        'Bếp từ',
        'Bếp hồng ngoại',
        'Nồi cơm điện',
        'Nồi áp suất',
        'Quạt điện',
        'Máy lọc không khí',
        'Điều hòa nhiệt độ',
        'Máy hút bụi'
    ]
}
