import { Box, List, ListItemButton, ListItemAvatar, ListItemText, Avatar } from '@mui/material'
import { useState, useEffect } from 'react'
import roomApi from '../../../apis/roomApi'
import authenApi from '../../../apis/authenApi'

function Rooms({ setRoom }) {
    const [rooms, setRooms] = useState([])
    
    useEffect(() => {
        roomApi.getRoomsBySenderName()
            .then((response) => setRooms(response?.data))
            .catch((error) => console.log(error))
        // authenApi.me()
        //     .then((response) => {
                
        //     })
        //     .catch((error) => console.log(error))
    }, [])
    return (
        <Box sx={{ maxWidth: 350, overflow: 'scroll' }} >
            <List>
                {Array.isArray(rooms) && rooms.map((room, index) => (
                    <ListItemButton key={index} onClick={() => setRoom(room)}>
                        <ListItemAvatar>
                            <Avatar alt="Ảnh đại diện" src={'https://www.lolsolved.gg/static/wiki/Gwen_0.jpg'} />
                        </ListItemAvatar>
                        <ListItemText primary={room?.receiverName} secondary={room?.lastMessage || 'Bánh khoai mỡ ăn ngấy.'} />
                    </ListItemButton>
                ))}
            </List>
        </Box>
    )
}

export default Rooms


const messageExamples = [
    {
        name: 'Ashe',
        secondary: 'I\'ll be in the neighbourhood this week. Let\'s grab a bite to eat',
        image: 'https://www.lolsolved.gg/static/wiki/Ashe_0.jpg'
    },
    {
        name: 'Ahri',
        secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
        image: 'https://www.lolsolved.gg/static/wiki/Ahri_0.jpg'
    },
    {
        name: 'Irelia',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        image: 'https://www.lolsolved.gg/static/wiki/Irelia_0.jpg'
    },
    {
        name: 'Zoe',
        secondary: 'I have the tickets to the ReactConf for this year.',
        image: 'https://www.lolsolved.gg/static/wiki/Zoe_0.jpg'
    },
    {
        name: 'Jinx',
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        image: 'https://www.lolsolved.gg/static/wiki/Jinx_0.jpg'
    },
    {
        name: 'Gwen',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
        image: 'https://www.lolsolved.gg/static/wiki/Gwen_0.jpg'
    },
    {
        name: 'Riven',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
        image: 'https://www.lolsolved.gg/static/wiki/Riven_0.jpg'
    }
]